#!/bin/bash
set -e #任何命令出错就退出
set -o pipefail

APP_ID=sr
APP_DIR="/data/app"

nohup java -Dspring.profiles.active=dev -jar ${APP_DIR}/${APP_ID}/${APP_ID}.jar >release_out.long &
start_ok=false
if [[ $? = 0 ]]; then
  sleep 3
  tail -n 10 release_out.log
  sleep 5
  tail -n 50 release_out.log
fi
aaa=$(grep "Started" release_out.log | awk '{print $1}')
if [[ -n "${aaa}" ]]; then
    echo "Application started ok"
    exit 0
else
  echo "Application started error"
  exit 1
fi